package com.iyzipay.audit;

public enum AuditEventType {
    REFUND_REQUEST_INITIATED,
    REFUND_REQUEST_RETRIED,
    REFUND_CACHE_HIT,
    REFUND_CACHE_MISS,
    REFUND_SUCCESS,
    REFUND_FAILED,
    REFUND_THROTTLED,
    REFUND_MANUAL_REVIEW_TRIGGERED,
    REFUND_IDEMPOTENCY_KEY_GENERATED,
    REFUND_RESPONSE_CACHED
}
